/* ============================================================
   Client-side report generation — genuinely downloads files.
   CSV is built by hand; PDF via jsPDF + jspdf-autotable.
   Nothing here touches a server.
   ============================================================ */
import { jsPDF } from 'jspdf';
import { applyPlugin } from 'jspdf-autotable';
import { formatDate, formatDateTime } from './format';

// jspdf-autotable ships a UMD bundle whose default export does not survive
// CJS/ESM interop consistently. Binding the plugin to our own jsPDF class is
// interop-proof and guarantees doc.autoTable exists.
applyPlugin(jsPDF);

const BRAND = [21, 94, 239];
const BRAND_DARK = [11, 59, 140];
const TEAL = [20, 184, 166];
const INK = [16, 24, 40];
const INK_2 = [71, 84, 103];
const LINE = [234, 236, 240];
const SUNK = [246, 248, 250];

export function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function stamp() {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}-${String(d.getHours()).padStart(2, '0')}${String(d.getMinutes()).padStart(2, '0')}`;
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/* ------------------------------------------------------------
   CSV
   ------------------------------------------------------------ */
function csvCell(v) {
  if (v === null || v === undefined) return '';
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/**
 * @param {{name:string, columns:{key:string,label:string,get?:Function}[], rows:object[], summary?:{label:string,value:any}[], meta?:{label:string,value:any}[]}} cfg
 * @returns {string} the filename written
 */
export function exportCsv({ name, columns, rows, summary = [], meta = [] }) {
  const lines = [];
  lines.push(`UrbanSight AI — ${name}`);
  lines.push(`Generated,${csvCell(formatDateTime(Date.now()))}`);
  meta.forEach((m) => lines.push(`${csvCell(m.label)},${csvCell(m.value)}`));
  if (summary.length) {
    lines.push('');
    lines.push('Summary');
    summary.forEach((s) => lines.push(`${csvCell(s.label)},${csvCell(s.value)}`));
  }
  lines.push('');
  lines.push(columns.map((c) => csvCell(c.label)).join(','));
  rows.forEach((r) => {
    lines.push(columns.map((c) => csvCell(c.get ? c.get(r) : r[c.key])).join(','));
  });

  const filename = `urbansight-${slugify(name)}-${stamp()}.csv`;
  // BOM keeps Excel happy with UTF-8
  triggerDownload(new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' }), filename);
  return filename;
}

/* ------------------------------------------------------------
   PDF
   ------------------------------------------------------------ */
function drawHeader(doc, name) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, W, 24, 'F');

  // logo mark
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(14, 6.5, 11, 11, 2.4, 2.4, 'F');
  doc.setFillColor(...BRAND);
  doc.circle(19.5, 12, 3.5, 'F');
  doc.setFillColor(...TEAL);
  doc.circle(19.5, 12, 1.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('UrbanSight AI', 29, 11.4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.6);
  doc.text('AI City Intelligence Platform', 29, 16.4);

  doc.setFontSize(8);
  doc.text('Greater Chennai Corporation', W - 14, 11.4, { align: 'right' });
  doc.setFontSize(7.2);
  doc.text('Tamil Nadu, India', W - 14, 16.2, { align: 'right' });
}

function drawFooter(doc, pageNo, pageCount) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.3);
  doc.line(14, H - 14, W - 14, H - 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.4);
  doc.setTextColor(152, 162, 179);
  doc.text('Generated by UrbanSight AI — data from bus-mounted AI camera detections.', 14, H - 9.5);
  doc.text(`Page ${pageNo} of ${pageCount}`, W - 14, H - 9.5, { align: 'right' });
}

function drawSummary(doc, summary, startY) {
  if (!summary.length) return startY;
  const W = doc.internal.pageSize.getWidth();
  const usable = W - 28;
  const perRow = Math.min(4, summary.length);
  const gap = 4;
  const boxW = (usable - gap * (perRow - 1)) / perRow;
  const boxH = 17;
  let y = startY;

  summary.forEach((s, i) => {
    const col = i % perRow;
    if (col === 0 && i > 0) y += boxH + gap;
    const x = 14 + col * (boxW + gap);
    doc.setFillColor(...SUNK);
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, y, boxW, boxH, 2, 2, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...INK_2);
    doc.text(String(s.label).toUpperCase(), x + 4, y + 6);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(...INK);
    doc.text(String(s.value), x + 4, y + 13.4);
  });
  return y + boxH + 8;
}

/**
 * Assemble the report document. Split out from exportPdf so the layout
 * can be exercised without a browser download.
 * @returns {jsPDF}
 */
export function buildPdfDoc({ name, subtitle, meta = [], summary = [], columns, rows, breakdown = null, note = '' }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: columns.length > 7 ? 'landscape' : 'portrait' });
  const W = doc.internal.pageSize.getWidth();

  drawHeader(doc, name);

  // title block
  let y = 34;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(...INK);
  doc.text(name, 14, y);
  y += 6;

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.4);
    doc.setTextColor(...INK_2);
    doc.text(subtitle, 14, y);
    y += 5.5;
  }

  // meta line
  const metaLine = [`Generated ${formatDateTime(Date.now())}`, ...meta.map((m) => `${m.label}: ${m.value}`)].join('   •   ');
  doc.setFontSize(8);
  doc.setTextColor(152, 162, 179);
  doc.text(doc.splitTextToSize(metaLine, W - 28), 14, y);
  y += 4.5 + (doc.splitTextToSize(metaLine, W - 28).length - 1) * 4;

  doc.setDrawColor(...LINE);
  doc.setLineWidth(0.4);
  doc.line(14, y, W - 14, y);
  y += 8;

  // summary tiles
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text('Summary', 14, y);
  y += 4;
  y = drawSummary(doc, summary, y);

  // optional breakdown table
  if (breakdown && breakdown.rows.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    doc.text(breakdown.title, 14, y);
    doc.autoTable({
      startY: y + 3,
      head: [breakdown.columns.map((c) => c.label)],
      body: breakdown.rows.map((r) => breakdown.columns.map((c) => (c.get ? c.get(r) : r[c.key]))),
      theme: 'grid',
      styles: { font: 'helvetica', fontSize: 8.4, cellPadding: 2.2, textColor: INK, lineColor: LINE, lineWidth: 0.2 },
      headStyles: { fillColor: BRAND_DARK, textColor: 255, fontStyle: 'bold', fontSize: 8.2 },
      alternateRowStyles: { fillColor: [251, 252, 253] },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 9;
  }

  // main data table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text(`Detail — ${rows.length} record${rows.length === 1 ? '' : 's'}`, 14, y);

  doc.autoTable({
    startY: y + 3,
    head: [columns.map((c) => c.label)],
    body: rows.map((r) => columns.map((c) => (c.get ? c.get(r) : r[c.key]))),
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 7.8, cellPadding: 2, textColor: INK, lineColor: LINE, lineWidth: 0.2, overflow: 'linebreak' },
    headStyles: { fillColor: BRAND, textColor: 255, fontStyle: 'bold', fontSize: 7.8 },
    alternateRowStyles: { fillColor: [251, 252, 253] },
    margin: { left: 14, right: 14, top: 30 },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) drawHeader(doc, name);
    },
  });

  if (note) {
    const afterY = doc.lastAutoTable.finalY + 8;
    const H = doc.internal.pageSize.getHeight();
    if (afterY < H - 26) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(...INK_2);
      doc.text(doc.splitTextToSize(note, W - 28), 14, afterY);
    }
  }

  // footers on every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, i, pageCount);
  }

  return doc;
}

/**
 * Build and download a formatted PDF report.
 * @returns {string} the filename written
 */
export function exportPdf(cfg) {
  const doc = buildPdfDoc(cfg);
  const filename = `urbansight-${slugify(cfg.name)}-${stamp()}.pdf`;
  doc.save(filename);
  return filename;
}

/** Single entry point used by every "Download / Export" button. */
export function generateReport(format, cfg) {
  return format === 'CSV' || format === 'csv' ? exportCsv(cfg) : exportPdf(cfg);
}

/* ------------------------------------------------------------
   Column presets used across pages
   ------------------------------------------------------------ */
export const ISSUE_COLUMNS = [
  { key: 'id', label: 'Report ID' },
  { key: 'categoryLabel', label: 'Category' },
  { key: 'area', label: 'Area' },
  { key: 'district', label: 'District' },
  { key: 'zone', label: 'Zone' },
  { key: 'severity', label: 'Severity', get: (r) => r.severity.charAt(0).toUpperCase() + r.severity.slice(1) },
  { key: 'priority', label: 'Priority' },
  { key: 'status', label: 'Status', get: (r) => r.status.replace('_', ' ').replace(/\b\w/g, (m) => m.toUpperCase()) },
  { key: 'confidence', label: 'AI Conf.', get: (r) => `${r.confidence}%` },
  { key: 'detectedAt', label: 'Detected', get: (r) => formatDate(r.detectedAt) },
];

export const INCIDENT_COLUMNS = [
  { key: 'id', label: 'Incident ID' },
  { key: 'typeLabel', label: 'Type' },
  { key: 'plate', label: 'Number Plate' },
  { key: 'ocrConfidence', label: 'OCR Conf.', get: (r) => `${r.ocrConfidence}%` },
  { key: 'area', label: 'Location' },
  { key: 'district', label: 'District' },
  { key: 'status', label: 'Status' },
  { key: 'detectedAt', label: 'Detected', get: (r) => formatDate(r.detectedAt) },
];
